Repository Callbritton/adopt_dont_shop_paired, pull requests merged in 2020-08, with the labels that each got.

#3 User four
  README.md
  app/controllers/reviews_controller.rb
  app/views/layouts/application.html.erb
  app/views/reviews/new.html.erb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  log/development.log
  spec/features/reviews/new_spec.rb
  tmp/cache/assets/sprockets/v3.0/1J/1JnNlMoorvDaAcLChcV1QOiqJyanmoUydnfe5-TPuXM.cache
  tmp/cache/assets/sprockets/v3.0/26/26srjO24hCUUux8qGnULMdK-aMjj8Pcab2z0M-WDtuo.cache
  tmp/cache/assets/sprockets/v3.0/41/41_29mpjEGapjHdofSi36OnnO3-eBNYbCe5nzHnIKwY.cache
  tmp/cache/assets/sprockets/v3.0/4z/4zs_2d1l8fnSEbeJMgzi5VH_VsW9cYsnHSz4FBm2jkg.cache
  tmp/cache/assets/sprockets/v3.0/61/61DYE6KWkT0kZHOqhoDyZVE-tFnswqDzUluEf04Z9qI.cache
  tmp/cache/assets/sprockets/v3.0/99/99m8UCKl4j8IpsVOK8ltLHyNh8Ae0nHw3GBkC34V_co.cache
  tmp/cache/assets/sprockets/v3.0/B4/B43LeT9Wba4fLvXw-C_kKq-x9HwYZxnBBiltbIufzzQ.cache
  tmp/cache/assets/sprockets/v3.0/HC/HCDOUd7-S45aJ_PjVAC_Vmjyud3i1aQv4cE3t9_Z3Dw.cache
  tmp/cache/assets/sprockets/v3.0/dt/dtojDzjuRf237nsZQwLv6An2Aey6QF9HjsHk3fUvgbA.cache
  tmp/cache/assets/sprockets/v3.0/jI/jI0HewMIz3uBejpKpYe5NZQFAo0-JxrJ-A5lo7zzH08.cache
  tmp/cache/assets/sprockets/v3.0/sb/sbdra4MXru4fxHN_jrd3o4d3VFPFyG3lI247mddfTUk.cache
  tmp/cache/bootsnap-load-path-cache
Labels: Ready to merge, Tests PASSING

#4 User five
  app/controllers/reviews_controller.rb
  app/views/reviews/edit.html.erb
  app/views/shelters/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  log/development.log
  spec/features/reviews/edit_spec.rb
  tmp/cache/assets/sprockets/v3.0/1J/1JnNlMoorvDaAcLChcV1QOiqJyanmoUydnfe5-TPuXM.cache
  tmp/cache/assets/sprockets/v3.0/41/41_29mpjEGapjHdofSi36OnnO3-eBNYbCe5nzHnIKwY.cache
  tmp/cache/assets/sprockets/v3.0/HC/HCDOUd7-S45aJ_PjVAC_Vmjyud3i1aQv4cE3t9_Z3Dw.cache
  tmp/cache/assets/sprockets/v3.0/sb/sbdra4MXru4fxHN_jrd3o4d3VFPFyG3lI247mddfTUk.cache
  tmp/cache/bootsnap-load-path-cache
Labels: Ready to merge, Tests PASSING, peer reviewed

#5 User seven
  README.md
  app/controllers/reviews_controller.rb
  app/views/shelters/show.html.erb
  config/routes.rb
  spec/features/reviews/delete_spec.rb
  spec/features/reviews/edit_spec.rb
  tmp/cache/bootsnap-load-path-cache
Labels: Ready to merge, Tests PASSING

#6 Adds user story 8 functionality
  app/views/layouts/application.html.erb
  log/development.log
  spec/features/favorites/nav_bar_spec.rb
  tmp/cache/assets/sprockets/v3.0/1J/1JnNlMoorvDaAcLChcV1QOiqJyanmoUydnfe5-TPuXM.cache
  tmp/cache/assets/sprockets/v3.0/41/41_29mpjEGapjHdofSi36OnnO3-eBNYbCe5nzHnIKwY.cache
  tmp/cache/assets/sprockets/v3.0/HC/HCDOUd7-S45aJ_PjVAC_Vmjyud3i1aQv4cE3t9_Z3Dw.cache
  tmp/cache/bootsnap-load-path-cache
Labels: Ready to merge, Tests PASSING

#8 User nine
  app/controllers/favorites_controller.rb
  app/views/pets/show.html.erb
  config/routes.rb
  spec/features/favorites/new_spec.rb
Labels: Ready to merge, driver/navigator peer-tested

#10 User story nine iii
  app/controllers/application_controller.rb
  app/controllers/favorites_controller.rb
  app/models/favorite.rb
  app/views/layouts/application.html.erb
  app/views/pets/show.html.erb
  log/development.log
  spec/features/favorites/nav_bar_spec.rb
  spec/features/favorites/new_spec.rb
  spec/models/favorite_spec.rb
Labels: Ready to merge, Tests PASSING, driver/navigator peer-tested

#11 User ten ii
  app/controllers/favorites_controller.rb
  app/models/favorite.rb
  app/views/favorites/index.html.erb
  config/routes.rb
  log/development.log
  spec/features/favorites/index_spec.rb
Labels: Ready to merge, Tests PASSING, driver/navigator peer-tested

#12 User eleven
  .gitignore
  README.md
  app/views/layouts/application.html.erb
  log/.keep
  log/development.log
  spec/features/favorites/index_spec.rb
Labels: Ready to merge, Tests PASSING, driver/navigator peer-tested

#13 User story 12
  Gemfile.lock
  app/controllers/favorites_controller.rb
  app/models/favorite.rb
  app/views/favorites/index.html.erb
  app/views/pets/show.html.erb
  config/routes.rb
  spec/features/favorites/delete_spec.rb
  spec/features/favorites/index_spec.rb
Labels: Ready to merge, Tests PASSING

#15 User fourteen
  README.md
  app/models/favorite.rb
  app/views/favorites/index.html.erb
  spec/features/favorites/index_spec.rb
Labels: Ready to merge, Tests PASSING

#17 User fifteen ii
  app/controllers/favorites_controller.rb
  app/models/favorite.rb
  app/views/favorites/index.html.erb
  config/routes.rb
  spec/features/favorites/index_spec.rb
Labels: Ready to merge, Tests PASSING
